spring.application.name=Substation Manager
server.port=${PORT:8080}

#MVC Configuration
spring.mvc.hiddenmethod.filter.enabled=true

#Base Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
logging.level.org.hibernate.persister.entity=ERROR

#Formula Configuration
microservice.url=https://energy-formula-svc.up.railway.app/api/v1
formula.api.key=secretKey123

#Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

#Security logs
logging.level.org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter=OFF

#Messages Configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8
