spring.application.name=Substation Manager
server.port=${PORT:8080}

#MVC Configuration
spring.mvc.hiddenmethod.filter.enabled=true

#Base Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
logging.level.org.hibernate.persister.entity=ERROR

#Formula Configuration
formula.api.key=secretKey123

#Cloudinary Configuration
cloudinary.cloud_name=demhlqrje
cloudinary.api_key=358836187285485
cloudinary.api_secret=07RayAgz1gWGTMOFTw5VMH5MKUY

#Security logs
logging.level.org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter=OFF

#Messages Configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8
